Badger-Finance/badger-sdk

src/graphql/index.ts

Allow graph to query individual user accounts.

chore: add user query

---

.github/workflows/test.yml
README.md
docs/local-testing.md
yarn.lock

- update README for modular documentation
- update test action for coverage reports

chore: update test workflow, add local development doc, update README

---

src/registry/registry.service.ts
src/sdk.ts
src/vaults/interfaces/get-vault-strategy-options.interface.ts
src/vaults/interfaces/index.ts
src/vaults/interfaces/list-harvest-options.interface.ts
src/vaults/interfaces/list-vault-options.interface.ts
src/vaults/vaults.service.ts

Require vault versions when requesting vault actions

refactor: require vault versions in service methods

---

src/api/index.ts
src/api/interfaces/index.ts
src/api/interfaces/reward-schedules-summary.interface.ts

- Add API calls for vault schedules request

fix: support schedules api

---

src/api/enums/currency.enum.ts
src/api/enums/protocol.enum.ts

chore: add potential protocols + btc currency

---

src/tokens/tokens.service.ts

Adds token approvals, revokes, and allowance look ups

fix: enable token service allowance checks and increases

---

src/config/enums/network.enum.ts
src/config/network/network.config.ts

feat: optimism

---

src/citadel/citadel.service.ts

Update staked citadel locker addr

fix: update citadel locker addr

---

mocks.pkg/package.json
mocks.pkg/src/config/services.config.ts

Fix Optimism mocks generator + bump mocks version

fix: update mocks gen

---

src/citadel/citadel.service.ts

Allows block queries on all citadel functions

fix: citadel support override

---

src/tests/interfaces/mock-vault-system.interface.ts
src/tests/tests.utils.ts
src/vaults/vaults.service.spec.ts

Add easy to use SDK / Vault mocks for testing.

chore: add initial testing harness functions

---

jest.config.js
src/tests/tests.constants.ts
src/tests/tests.utils.ts
src/tokens/__snapshots__/tokens.service.spec.ts.snap
src/tokens/interfaces/index.ts
src/tokens/interfaces/revoke-allowance-options.interface.ts
src/tokens/tokens.service.spec.ts
src/tokens/tokens.service.ts

Completes the `tokens.service.ts` test coverage for all methods in all branches save input differences.

chore: add full increase allowance coverage

---

src/config/interfaces/index.ts
src/config/interfaces/transaction-callback-input.interface.ts
src/config/interfaces/transaction-options.interface.ts
src/rewards/interfaces/claim-options.interface.ts
src/rewards/rewards.service.ts
src/tokens/interfaces/token-action-callback-input.interface.ts
src/tokens/interfaces/token-action-options.interface.ts

Add relevant hooks for SDK badger tree claim

fix: upgrade claim for ui usage

---

mocks.pkg/__cache__/methods.json
mocks.pkg/generated/ethereum/api/loadVaultHarvests.json
mocks.pkg/generated/ethereum/api/loadVaultsHarvests.json
mocks.pkg/src/config/base.config.ts
src/api/enums/harvest-type.enum.ts
src/api/enums/index.ts
src/api/index.ts
src/api/interfaces/index.ts
src/api/interfaces/vault-earning.interface.ts

Add support for querying harvest data

chore: add vault harvest query support

---

src/ibbtc/ibbtc.service.ts
src/service.ts

Fixes issue resulting in a provider utilization when a signer is active but an address has not been assigned yet.

fix: change connector resolver

---

src/tokens/interfaces/token-action-options.interface.ts
src/tokens/tokens.service.ts

chore: add tx receipt context to approval callbacks

---

mocks.pkg/__cache__/methods.json
mocks.pkg/generated/ethereum/api/loadProtocolSummary.json
src/api/index.ts

fix: protocol value api missing version path

---

package.json
src/config/constants.ts
src/digg/digg.service.ts
src/ibbtc/ibbtc.service.ts
src/registry/registry.service.ts
src/rewards/rewards.service.ts
src/sdk.ts
src/vaults/vaults.service.ts
yarn.lock

- removed global references from objects

fix: test compatibilities

---

mocks.pkg/__cache__/methods.json
mocks.pkg/generated/ethereum/vaults/listHarvests.json
src/vaults/vaults.service.ts

fix: update overrides inputs + update mocks

---

src/graphql/fragments/sett.fragment.graphql
src/graphql/generated/badger.ts

- adds support for querying created at block
[
[#block](https://github.com/Badger-Finance/badger-api/issues/1504)](https://github.com/Badger-Finance/badger-api/issues/1504)

fix: add created at block to query

---

mocks.pkg/generated/ethereum/graph/loadSett.json
mocks.pkg/generated/ethereum/graph/loadSetts.json

fix: update graph mocks

---

src/vaults/vaults.service.ts

- support known developer vaults

fix: allow development vaults on load

---

src/vaults/vaults.service.ts

- allow fallback for vault with non standard deposit abi

fix: update vault deposit attempt
